version: '3.8'

services:
  app:
    build: .
    ports:
    - "8080:8080"
    environment:
        DB_URL: ${DB_URL}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        BOT_TOKEN: ${BOT_TOKEN}
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: