--liquibase formatted sql

--changeset basma:insert-steps
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Bitter Sweet', 'FEMALE', 'Kayti Insanity', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Naughty or nice', 'FEMALE', 'Kayti Insanity', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Dancehall vogue', 'FEMALE', 'Kayti Insanity', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Unfold', 'FEMALE', 'Kayti Insanity', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Uppercut', 'FEMALE', 'Smilez TopNotch', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Mush up', 'FEMALE', 'Smilez TopNotch', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Pully', 'FEMALE', 'Dancing Rebel', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'A dat that u want', 'FEMALE', 'Dancing Rebel', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Non stop', 'FEMALE', 'Dancing Rebel', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Swiss', 'FEMALE', 'Dancing Rebel', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Still in love', 'FEMALE', 'Inspire', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Excuse me', 'FEMALE', 'Nieka OG', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Flossy whine', 'FEMALE', 'Nieka OG', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Hot flash', 'FEMALE', 'Nieka OG', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Prada', 'FEMALE', 'Wazzi', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Badish', 'FEMALE', 'Darkie', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Motion', 'FEMALE', 'Kayburr', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Strawberry', 'FEMALE', 'Mama Blazzaz', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Sweet whine', 'FEMALE', 'Mama Blazzaz', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Attitude', 'FEMALE', 'Mama Blazzaz', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Copycat', 'FEMALE', 'Mama Blazzaz', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'O mama', 'FEMALE', 'Mama Blazzaz', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Aquatic', 'FEMALE', 'Mama Blazzaz', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Bounce&Clap', 'FEMALE', 'Mama Blazzaz', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Affi touch', 'FEMALE', 'Mama Blazzaz', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Gyal wine', 'FEMALE', 'Reda TopNotch', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Versatile', 'FEMALE', 'Latonya style', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Original rude gyal', 'FEMALE', 'Latonya style', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Nuff respect', 'FEMALE', 'Latonya style', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Mush up', 'FEMALE', 'Latonya style', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Back&Forth', 'FEMALE', 'Dancing Rebel', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Couple up (juk)', 'FEMALE', NULL, 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Sexy body gyal', 'FEMALE', 'Latonya style', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Hardcore', 'FEMALE', 'Latonya style', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Above average', 'FEMALE', 'Latonya style', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Badaboom', 'FEMALE', 'Kimiko Versatile', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Sweet like sugar', 'FEMALE', 'Kimiko Versatile', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Cocky broka', 'FEMALE', 'Kimiko Versatile', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Wind speed', 'FEMALE', 'Inspire', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Immortality', 'FEMALE', 'Baby Girl', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Outshine', 'FEMALE', 'Outshine Team', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Perfect', 'FEMALE', 'Kissy Mckoy', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Shapeylous', 'FEMALE', 'Kayti Insanity', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Chrome whine', 'FEMALE', 'Nikki Chromaz', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Tilt and whine', 'FEMALE', NULL, 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Skettle', 'FEMALE', NULL, 'OLD');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Dutty whine', 'FEMALE', NULL, 'MIDDLE');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Big&Nasty', 'FEMALE', 'Xpressionz', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Go go whine', 'FEMALE', NULL, 'OLD');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Hot wuk', 'FEMALE', NULL, 'MIDDLE');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Hula hoop', 'FEMALE', NULL, 'MIDDLE');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Steady wine', 'FEMALE', NULL, 'MIDDLE');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Tempa wine', 'FEMALE', 'Kartoon', 'MIDDLE');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Tic Toc', 'FEMALE', NULL, 'MIDDLE');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Walk&Shake', 'FEMALE', NULL, 'MIDDLE');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Butterfly', 'FEMALE', NULL, 'OLD');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Slide and wine', 'FEMALE', NULL, 'OLD');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Wata pumpie', 'FEMALE', NULL, 'OLD');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Juk it', 'FEMALE', 'Xpressionz', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Naked', 'FEMALE', 'Xpressionz', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'One knock', 'FEMALE', 'Xpressionz', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Good body', 'FEMALE', 'Xpressionz', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Tender touch', 'FEMALE', 'Xpressionz', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Clap Yuself', 'FEMALE', 'Latonya style', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Jiggle it', 'FEMALE', 'Latonya style', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Pretty wine', 'FEMALE', 'Latonya style', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Dig it', 'FEMALE', 'Kimiko Versatile', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Jafrican whine', 'FEMALE', 'Kimiko Versatile', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Fabulus', 'FEMALE', 'Stacya Fia', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'I-bless', 'FEMALE', 'Stacya Fia', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Ketch a fire', 'FEMALE', 'Kim Weezy', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Weezy wine', 'FEMALE', 'Kim Weezy', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Close up', 'FEMALE', 'Dancing Rebel', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Pon di spot', 'FEMALE', 'Dancing Rebel', 'EARLY_NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'XO motion', 'FEMALE', 'Sara Bendii', 'NEW');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Happy jook', 'FEMALE', 'Happyfeet', 'UNKNOWN');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Badumboom', 'FEMALE', 'Xqlusiv', 'UNKNOWN');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Cursive', 'FEMALE', 'Team Cautiion', 'UNKNOWN');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Sneak Peak', 'FEMALE', 'Team Cautiion', 'UNKNOWN');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Lowkey', 'FEMALE', 'Ultimate Girlz', 'UNKNOWN');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Hanky panky', 'FEMALE', 'Barbie Chelsea', 'UNKNOWN');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Shorty Infinity', 'FEMALE', 'Shorty Dancershine', 'UNKNOWN');
insert into step(id, name, type, author, era) values (nextval('step_sequence'), 'Hurricane Bendii', 'FEMALE', 'Sara Bendii', 'UNKNOWN');