on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: connect, pull and run
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.PROJECT_FOLDER }}
            git checkout main
            git pull origin main
            mvn clean package
            podman-compose down
            podman-compose --env-file ../app/env.sh up -d
            EOF